/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */


/**
 * An event that is sent when the number of visible markers is changed. Tracking coordinates for the markers is going to be sent with some other approach.
 *
 * @event module:markerdetector#MarkerCount
 *
 * @type {module:markerdetector#event:Media}
 *
 * @property {external:Integer} markerId
 *  marker id
 * @property {external:Integer} markerCount
 *  Number of visible markers with the specified id
 * @property {external:Integer} markerCountDiff
 *  How much the markerCount was changed from the previous situation
 */
